name: taxcrunch-env
channels:
- PSLmodels
- conda-forge
dependencies:
- python>=3.6.5
- taxcalc>=3.0.0
- behresp>=0.9.0
- pandas>=0.23
- numpy>=1.13
- paramtools>=0.10.1
- pytest
- bokeh<2.0.0
- coverage
- pip
- pip:
  - cs-kit
